export default [
  {
    ignores: ["dist/**", "node_modules/**"],
  },
  {
    files: ["js/**/*.js", "tests/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        AbortController: "readonly",
        Blob: "readonly",
        Chart: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        FormData: "readonly",
        HTMLElement: "readonly",
        Node: "readonly",
        Notification: "readonly",
        PerformanceObserver: "readonly",
        Promise: "readonly",
        Response: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        WebSocket: "readonly",
        alert: "readonly",
        atob: "readonly",
        btoa: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        confirm: "readonly",
        console: "readonly",
        crypto: "readonly",
        document: "readonly",
        fetch: "readonly",
        IntersectionObserver: "readonly",
        CONFIG: "readonly",
        localStorage: "readonly",
        navigator: "readonly",
        performance: "readonly",
        queueMicrotask: "readonly",
        requestAnimationFrame: "readonly",
        requestIdleCallback: "readonly",
        sessionStorage: "readonly",
        setInterval: "readonly",
        setTimeout: "readonly",
        structuredClone: "readonly",
        window: "readonly",
      },
    },
    rules: {
      "no-redeclare": "error",
      "no-undef": "error",
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],
    },
  },
];
