#!/bin/bash
# Phase 2 Integration Instructions

echo "========================================="
echo "QSOP Phase 2 Integration Guide"
echo "========================================="
echo ""

echo "1. Install new Python dependencies:"
echo "   pip install redis[msgpack] msgpack cryptography"
echo "   pip install azure-identity azure-keyvault-secrets"
echo ""

echo "2. Configure environment variables:"
echo "   # Add to .env or docker-compose.yml"
echo ""
echo "   # Credential Storage"
echo "   CREDENTIAL_STORAGE_MODE=local  # Options: local, azure, demo"
echo "   # For Azure:"
echo "   AZURE_KEY_VAULT_URL=https://your-vault.vault.azure.net/"
echo "   # For local/dev only:"
echo "   LOCAL_ENCRYPTION_KEY=your-32-byte-key-here"
echo ""
echo "   # Redis"
echo "   REDIS_MODE=optional  # Options: optional, required"
echo "   REDIS_URL=redis://localhost:6379/0"
echo "   REDIS_POOL_SIZE=10"
echo ""

echo "3. Update api/main.py to initialize new services:"
echo ""
echo "   # Add imports"
echo "   from api.services.credentials import init_credential_manager, close_credential_manager"
echo "   from api.services.redis_client import init_redis, close_redis"
echo "   from api.routers import credentials"
echo "   from api.routers.health_v2 import router as health_v2_router"
echo ""
echo "   # In lifespan startup:"
echo "   await init_credential_manager()"
echo "   await init_redis()"
echo ""
echo "   # In lifespan shutdown:"
echo "   await close_credential_manager()"
echo "   await close_redis()"
echo ""
echo "   # Register new routers:"
echo "   api_v1_router.include_router(credentials.router, prefix='/credentials', tags=['Credentials'])"
echo "   # Replace health router:"
echo "   app.include_router(health_v2_router, tags=['Health'])"
echo ""

echo "4. Redis setup (optional in development):"
echo ""
echo "   # Using Docker:"
echo "   docker run -d -p 6379:6379 redis:7-alpine"
echo ""
echo "   # Or add to docker-compose.yml:"
echo "   redis:"
echo "     image: redis:7-alpine"
echo "     ports:"
echo "       - '6379:6379'"
echo "     volumes:"
echo "       - redis_data:/data"
echo ""

echo "5. Test the new endpoints:"
echo ""
echo "   # Health check (comprehensive)"
echo "   curl http://localhost:8000/health/full"
echo ""
echo "   # Credentials API"
echo "   curl -X POST http://localhost:8000/api/v1/credentials \\"
echo "     -H 'Authorization: Bearer YOUR_TOKEN' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{"
echo "       \"provider\": \"ibm\","
echo "       \"credential_type\": \"api_token\","
echo "       \"value\": \"your-api-token-here\""
echo "     }'"
echo ""
echo "   # List credentials"
echo "   curl http://localhost:8000/api/v1/credentials \\"
echo "     -H 'Authorization: Bearer YOUR_TOKEN'"
echo ""

echo "6. Frontend updates:"
echo ""
echo "   # Remove btoa() credential storage from dashboard.js"
echo "   # Use /api/v1/credentials endpoints instead"
echo "   # Add credential management UI"
echo ""

echo "7. Migration from in-memory to Redis:"
echo ""
echo "   # Run migration script (to be created):"
echo "   python scripts/migrate_to_redis.py"
echo ""
echo "   # Or manually in main.py startup:"
echo "   from api.storage.redis_adapter import migrate_in_memory_to_redis, get_redis_store"
echo "   from api.routers.auth import _users_db, _tokens_db"
echo "   from api.routers.jobs import _jobs_db"
echo ""
echo "   users_store = get_redis_store('users')"
echo "   jobs_store = get_redis_store('jobs')"
echo "   tokens_store = get_redis_store('tokens')"
echo ""
echo "   await migrate_in_memory_to_redis(_users_db, users_store)"
echo "   await migrate_in_memory_to_redis(_jobs_db, jobs_store)"
echo "   await migrate_in_memory_to_redis(_tokens_db, tokens_store)"
echo ""

echo "========================================="
echo "Integration complete!"
echo "========================================="
