"""RFC 7807 Problem Details (Error responses)."""

from __future__ import annotations

from datetime import datetime
from typing import Any
from urllib.parse import urlencode
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, HttpUrl

PROBLEM_TYPE_BASE = "https://api.qsop.example.com/errors/"


class ProblemDetail(BaseModel):
    """
    RFC 7807 Problem Details for HTTP APIs.

    Standardized error response format for machine-readable details of errors.
    See: https://datatracker.ietf.org/doc/html/rfc7807
    """

    type: str = Field(
        default=PROBLEM_TYPE_BASE + "general",
        description="A URI reference [RFC3986] that identifies the problem type",
        examples=[PROBLEM_TYPE_BASE + "validation-error"],
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type",
        examples=["Validation Error", "Not Found", "Unauthorized"],
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server for this problem",
        examples=[400, 404, 401, 500],
    )
    detail: str = Field(
        ...,
        description="A human-readable explanation specific to this occurrence of the problem",
        examples=["The requested resource was not found", "Invalid input parameters"],
    )
    instance: str | None = Field(
        default=None,
        description="A URI reference that identifies the specific occurrence of the problem",
        examples=["https://api.qsop.example.com/jobs/12345"],
    )
    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the error occurred",
    )
    request_id: str | None = Field(
        default=None,
        description="Unique request identifier for debugging",
        examples=["req_abc123xyz"],
    )
    errors: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Detailed list of validation or field errors",
        examples=[[{"field": "email", "message": "Invalid email format"}]],
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": PROBLEM_TYPE_BASE + "not-found",
                "title": "Resource Not Found",
                "status": 404,
                "detail": "Job with ID '550e8400-e29b-41d4-a716-446655440000' not found",
                "instance": "https://api.qsop.example.com/jobs/550e8400-e29b-41d4-a716-446655440000",
                "timestamp": "2024-01-15T10:30:00Z",
                "request_id": "req_abc123xyz",
                "errors": [],
            }
        }
    )


class ValidationErrorDetail(ProblemDetail):
    """Validation error with field-level details."""

    type: str = Field(default=PROBLEM_TYPE_BASE + "validation-error", frozen=True)
    title: str = Field(default="Validation Error", frozen=True)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": PROBLEM_TYPE_BASE + "validation-error",
                "title": "Validation Error",
                "status": 422,
                "detail": "The request could not be processed due to validation errors",
                "instance": "https://api.qsop.example.com/jobs",
                "timestamp": "2024-01-15T10:30:00Z",
                "request_id": "req_abc123xyz",
                "errors": [
                    {
                        "field": "problem_config.graph.nodes",
                        "message": "Must be a positive integer",
                        "type": "value_error.number.not_gt",
                    },
                    {
                        "field": "parameters.p",
                        "message": "Must be an integer between 1 and 10",
                        "type": "value_error.number.not_in_range",
                    },
                ],
            }
        }
    )


class AuthenticationErrorDetail(ProblemDetail):
    """Authentication/authorization error."""

    type: str = Field(default=PROBLEM_TYPE_BASE + "authentication-error", frozen=True)
    title: str = Field(default="Authentication Failed", frozen=True)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": PROBLEM_TYPE_BASE + "authentication-error",
                "title": "Authentication Failed",
                "status": 401,
                "detail": "Invalid or expired PQC token",
                "instance": "https://api.qsop.example.com/jobs",
                "timestamp": "2024-01-15T10:30:00Z",
                "request_id": "req_abc123xyz",
                "errors": [],
            }
        }
    )


class NotFoundErrorDetail(ProblemDetail):
    """Resource not found error."""

    type: str = Field(default=PROBLEM_TYPE_BASE + "not-found", frozen=True)
    title: str = Field(default="Resource Not Found", frozen=True)

    resource_type: str | None = Field(
        default=None,
        description="Type of resource that was not found",
        examples=["Job", "Key", "Algorithm"],
    )
    resource_id: str | UUID | None = Field(
        default=None,
        description="ID of the resource that was not found",
        examples=["550e8400-e29b-41d4-a716-446655440000"],
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": PROBLEM_TYPE_BASE + "not-found",
                "title": "Resource Not Found",
                "status": 404,
                "detail": "Job with ID '550e8400-e29b-41d4-a716-446655440000' not found",
                "instance": "https://api.qsop.example.com/jobs/550e8400-e29b-41d4-a716-446655440000",
                "timestamp": "2024-01-15T10:30:00Z",
                "request_id": "req_abc123xyz",
                "resource_type": "Job",
                "resource_id": "550e8400-e29b-41d4-a716-446655440000",
                "errors": [],
            }
        }
    )


class ConflictErrorDetail(ProblemDetail):
    """Conflict error (resource state inconsistency)."""

    type: str = Field(default=PROBLEM_TYPE_BASE + "conflict", frozen=True)
    title: str = Field(default="Conflict", frozen=True)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": PROBLEM_TYPE_BASE + "conflict",
                "title": "Conflict",
                "status": 409,
                "detail": "Job is already in a terminal state 'completed'",
                "instance": "https://api.qsop.example.com/jobs/550e8400-e29b-41d4-a716-446655440000/cancel",
                "timestamp": "2024-01-15T10:30:00Z",
                "request_id": "req_abc123xyz",
                "errors": [],
            }
        }
    )


class RateLimitErrorDetail(ProblemDetail):
    """Rate limit exceeded error."""

    type: str = Field(default=PROBLEM_TYPE_BASE + "rate-limit-exceeded", frozen=True)
    title: str = Field(default="Too Many Requests", frozen=True)

    retry_after: int | None = Field(
        default=None,
        description="Seconds until the request can be retried",
        examples=[60],
    )
    limit: int | None = Field(
        default=None,
        description="Rate limit applied",
        examples=[100],
    )
    remaining: int | None = Field(
        default=None,
        description="Remaining requests allowed",
        examples=[95],
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": PROBLEM_TYPE_BASE + "rate-limit-exceeded",
                "title": "Too Many Requests",
                "status": 429,
                "detail": "Rate limit exceeded. Please retry after 60 seconds.",
                "instance": "https://api.qsop.example.com/jobs",
                "timestamp": "2024-01-15T10:30:00Z",
                "request_id": "req_abc123xyz",
                "errors": [],
                "retry_after": 60,
                "limit": 100,
                "remaining": 0,
            }
        }
    )


class InternalErrorDetail(ProblemDetail):
    """Internal server error."""

    type: str = Field(default=PROBLEM_TYPE_BASE + "internal-error", frozen=True)
    title: str = Field(default="Internal Server Error", frozen=True)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": PROBLEM_TYPE_BASE + "internal-error",
                "title": "Internal Server Error",
                "status": 500,
                "detail": "An unexpected error occurred while processing the request",
                "instance": "https://api.qsop.example.com/jobs",
                "timestamp": "2024-01-15T10:30:00Z",
                "request_id": "req_abc123xyz",
                "errors": [],
            }
        }
    )
