"""
Property-based tests for cryptographic operations using Hypothesis.

Tests cryptographic invariants that must hold for all inputs:
- ML-KEM: encapsulate/decapsulate always produce matching secrets
- ML-DSA: sign/verify always work for any message
- AEAD: encrypt/decrypt roundtrips for all plaintexts
- HKDF: deterministic key derivation
"""

import pytest

try:
    from hypothesis import given, settings, strategies as st, HealthCheck
    HYPOTHESIS_AVAILABLE = True
except ImportError:
    HYPOTHESIS_AVAILABLE = False
    pytest.skip("Hypothesis not installed", allow_module_level=True)

import os


class TestMLKEMProperties:
    """Test ML-KEM (Kyber) cryptographic properties."""

    @given(st.binary(min_size=1, max_size=4096))
    @settings(max_examples=50, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_kem_encapsulate_decapsulate_roundtrip(self, seed):
        """
        Property: For all valid keypairs, decapsulate(encapsulate(pk)) == shared_secret
        
        This must hold for ANY keypair generated by the KEM.
        """
        try:
            import quantum_safe_crypto as pqc
            
            # Use seed to ensure deterministic behavior (for reproducibility)
            # In practice, we just test multiple random keypairs
            
            # Generate keypair
            kem = pqc.KemKeyPair()
            
            # Encapsulate
            ciphertext, shared_secret_1 = pqc.py_kem_encapsulate(kem.public_key)
            
            # Decapsulate
            shared_secret_2 = pqc.py_kem_decapsulate(ciphertext, kem.secret_key)
            
            # Property: Shared secrets must match
            assert shared_secret_1 == shared_secret_2, \
                "KEM roundtrip failed: encapsulated secret != decapsulated secret"
                
        except ImportError:
            pytest.skip("quantum_safe_crypto not available")

    @given(st.integers(min_value=1, max_value=100))
    @settings(max_examples=20)
    def test_kem_keypair_uniqueness(self, seed):
        """
        Property: Every generated keypair must be unique.
        
        No two keypairs should have the same public key.
        """
        try:
            import quantum_safe_crypto as pqc
            
            public_keys = set()
            
            for _ in range(10):
                kem = pqc.KemKeyPair()
                pk_hex = kem.public_key.hex()
                
                # Property: Public key must be unique
                assert pk_hex not in public_keys, \
                    "Duplicate public key generated!"
                public_keys.add(pk_hex)
                
        except ImportError:
            pytest.skip("quantum_safe_crypto not available")


class TestMLDSAProperties:
    """Test ML-DSA (Dilithium) cryptographic properties."""

    @given(st.binary(min_size=0, max_size=4096))
    @settings(max_examples=50)
    def test_mldsa_sign_verify_all_messages(self, message):
        """
        Property: For all messages, verify(sign(message, sk), pk) == True
        
        This must hold for ANY message (including empty).
        """
        try:
            import quantum_safe_crypto as pqc
            
            # Generate signing keypair
            sig = pqc.SigningKeyPair()
            
            # Sign message
            signature = sig.sign(message)
            
            # Verify signature
            is_valid = sig.verify(message, signature)
            
            # Property: Signature must be valid
            assert is_valid is True, \
                f"Signature verification failed for message of length {len(message)}"
                
        except ImportError:
            pytest.skip("quantum_safe_crypto not available")

    @given(st.binary(min_size=1, max_size=1024))
    @settings(max_examples=30)
    def test_mldsa_wrong_message_fails(self, message):
        """
        Property: verify(wrong_message, signature, pk) == False
        
        Signatures must NOT validate for different messages.
        """
        try:
            import quantum_safe_crypto as pqc
            
            sig = pqc.SigningKeyPair()
            
            # Sign original message
            original = b"original_message"
            signature = sig.sign(original)
            
            # Verify with different message
            is_valid = sig.verify(message, signature)
            
            # Property: Must fail for different message
            if message != original:
                assert is_valid is False, \
                    "Signature verified for wrong message!"
                
        except ImportError:
            pytest.skip("quantum_safe_crypto not available")

    @given(st.integers(min_value=1, max_value=100))
    @settings(max_examples=20)
    def test_mldsa_signature_uniqueness(self, seed):
        """
        Property: Signatures of different messages must be unique.
        """
        try:
            import quantum_safe_crypto as pqc
            
            sig = pqc.SigningKeyPair()
            signatures = set()
            
            for i in range(10):
                message = f"message_{i}".encode()
                signature = sig.sign(message)
                sig_hex = signature.hex()
                
                # Property: Each signature must be unique
                assert sig_hex not in signatures, \
                    "Duplicate signature generated!"
                signatures.add(sig_hex)
                
        except ImportError:
            pytest.skip("quantum_safe_crypto not available")


class TestAEADProperties:
    """Test AEAD encryption properties."""

    @given(st.binary(min_size=0, max_size=4096))
    @settings(max_examples=50)
    def test_aead_encrypt_decrypt_roundtrip(self, plaintext):
        """
        Property: decrypt(encrypt(plaintext, key, nonce), key, nonce) == plaintext
        
        Must hold for ALL plaintexts (including empty).
        """
        try:
            from cryptography.hazmat.primitives.ciphers.aead import AESGCM
            
            key = os.urandom(32)
            nonce = os.urandom(12)
            
            # Encrypt
            ciphertext = AESGCM(key).encrypt(nonce, plaintext, None)
            
            # Decrypt
            decrypted = AESGCM(key).decrypt(nonce, ciphertext, None)
            
            # Property: Must roundtrip correctly
            assert decrypted == plaintext, \
                f"AEAD roundtrip failed for plaintext of length {len(plaintext)}"
                
        except ImportError:
            pytest.skip("cryptography not available")

    @given(st.binary(min_size=1, max_size=1024), st.binary(min_size=1, max_size=128))
    @settings(max_examples=30)
    def test_aead_with_aad_roundtrip(self, plaintext, aad):
        """
        Property: AEAD must work correctly with any associated data.
        """
        try:
            from cryptography.hazmat.primitives.ciphers.aead import AESGCM
            
            key = os.urandom(32)
            nonce = os.urandom(12)
            
            # Encrypt with AAD
            ciphertext = AESGCM(key).encrypt(nonce, plaintext, aad)
            
            # Decrypt with same AAD
            decrypted = AESGCM(key).decrypt(nonce, ciphertext, aad)
            
            # Property: Must roundtrip
            assert decrypted == plaintext
                
        except ImportError:
            pytest.skip("cryptography not available")

    @given(st.binary(min_size=1, max_size=512))
    @settings(max_examples=30)
    def test_aead_tamper_detection(self, plaintext):
        """
        Property: Any tampering with ciphertext must be detected.
        """
        try:
            from cryptography.hazmat.primitives.ciphers.aead import AESGCM
            
            key = os.urandom(32)
            nonce = os.urandom(12)
            
            # Encrypt
            ciphertext = AESGCM(key).encrypt(nonce, plaintext, None)
            
            # Tamper with every byte
            for i in range(len(ciphertext)):
                tampered = bytearray(ciphertext)
                tampered[i] ^= 0xFF  # Flip bits
                
                # Property: Decryption must fail
                with pytest.raises(Exception):
                    AESGCM(key).decrypt(nonce, bytes(tampered), None)
                
        except ImportError:
            pytest.skip("cryptography not available")


class TestHKDFProperties:
    """Test HKDF key derivation properties."""

    @given(st.binary(min_size=1, max_size=256))
    @settings(max_examples=30)
    def test_hkdf_deterministic(self, ikm):
        """
        Property: HKDF(ikm, salt, info) must always produce same key for same inputs.
        """
        try:
            from cryptography.hazmat.primitives.kdf.hkdf import HKDF
            from cryptography.hazmat.primitives import hashes
            
            salt = b"test_salt"
            info = b"test_info"
            
            # Derive key twice
            hkdf1 = HKDF(
                algorithm=hashes.SHA256(),
                length=32,
                salt=salt,
                info=info,
            )
            key1 = hkdf1.derive(ikm)
            
            hkdf2 = HKDF(
                algorithm=hashes.SHA256(),
                length=32,
                salt=salt,
                info=info,
            )
            key2 = hkdf2.derive(ikm)
            
            # Property: Keys must match
            assert key1 == key2, \
                "HKDF is not deterministic!"
                
        except ImportError:
            pytest.skip("cryptography not available")

    @given(st.binary(min_size=1, max_size=128))
    @settings(max_examples=30)
    def test_hkdf_different_salt_different_keys(self, ikm):
        """
        Property: Different salts must produce different keys.
        """
        try:
            from cryptography.hazmat.primitives.kdf.hkdf import HKDF
            from cryptography.hazmat.primitives import hashes
            
            info = b"test_info"
            
            # Derive with different salts
            hkdf1 = HKDF(
                algorithm=hashes.SHA256(),
                length=32,
                salt=b"salt_1",
                info=info,
            )
            key1 = hkdf1.derive(ikm)
            
            hkdf2 = HKDF(
                algorithm=hashes.SHA256(),
                length=32,
                salt=b"salt_2",
                info=info,
            )
            key2 = hkdf2.derive(ikm)
            
            # Property: Keys must differ
            assert key1 != key2, \
                "Different salts produced same key!"
                
        except ImportError:
            pytest.skip("cryptography not available")

    @given(st.integers(min_value=16, max_value=128))
    @settings(max_examples=20)
    def test_hkdf_output_length(self, length):
        """
        Property: HKDF must produce output of exact requested length.
        """
        try:
            from cryptography.hazmat.primitives.kdf.hkdf import HKDF
            from cryptography.hazmat.primitives import hashes
            
            hkdf = HKDF(
                algorithm=hashes.SHA256(),
                length=length,
                salt=b"salt",
                info=b"info",
            )
            key = hkdf.derive(b"ikm")
            
            # Property: Output length must match
            assert len(key) == length, \
                f"HKDF output length {len(key)} != requested {length}"
                
        except ImportError:
            pytest.skip("cryptography not available")


class TestJobStateMachine:
    """Test job state machine properties."""

    @given(st.sampled_from(["QAOA", "VQE", "ANNEALING"]))
    @settings(max_examples=20)
    def test_valid_job_state_transitions(self, problem_type):
        """
        Property: Jobs must follow valid state transitions.
        
        Valid: queued → running → completed/failed
        Invalid: completed → running, failed → completed (without retry)
        """
        valid_states = ["queued", "running", "completed", "failed"]
        valid_transitions = {
            "queued": ["running", "failed"],
            "running": ["completed", "failed"],
            "completed": [],  # Terminal state
            "failed": ["queued"],  # Only via retry
        }
        
        # Test all valid transitions
        for from_state, to_states in valid_transitions.items():
            for to_state in to_states:
                # Property: Transition must be valid
                assert to_state in valid_transitions[from_state], \
                    f"Invalid transition: {from_state} → {to_state}"
